#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:file:C:/Users/mycat/Desktop/Server Side/neiu-cs-321/the-astrology-app/dbdata
#spring.datasource.username=admin
#spring.datasource.password=
#spring.datasource.driver-class-name=org.h2.Driver

---
spring:
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:C:/Users/mycat/Desktop/Server Side/neiu-cs-321/the-astrology-app/dbdata
    username: admin
    password:
    driver: org.h2.Driver

astrology:
  birthday:
    pageSize: 5

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error
